# Generated by Django 4.2.27 on 2025-12-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_dc_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='material_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=10, unique=True)),
                ('density_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='operator_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('inward_slip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('worker_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_dc_no', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('programer_status', models.CharField(default='pending', max_length=30)),
                ('outward_status', models.CharField(default='pending', max_length=30)),
                ('qa_status', models.CharField(default='pending', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user')),
            ],
        ),
        migrations.CreateModel(
            name='product_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.CharField(blank=True, max_length=50, null=True)),
                ('mat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mat_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('thick', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('unit_weight', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('stock_due', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('programer_status', models.CharField(default='pending', max_length=30)),
                ('qa_status', models.CharField(default='pending', max_length=30)),
                ('acc_status', models.CharField(default='pending', max_length=30)),
                ('product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Qa_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=30, null=True)),
                ('no_of_sheets', models.IntegerField(blank=True, null=True)),
                ('cycletime_per_sheet', models.FloatField(blank=True, null=True)),
                ('total_cycle_time', models.FloatField(blank=True, null=True)),
                ('machines_used', models.JSONField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user')),
                ('material_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_material')),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='programer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_no', models.CharField(blank=True, max_length=30, null=True)),
                ('program_date', models.DateField()),
                ('processed_quantity', models.FloatField(blank=True, null=True)),
                ('balance_quantity', models.FloatField(blank=True, null=True)),
                ('processed_width', models.FloatField(blank=True, null=True)),
                ('processed_length', models.FloatField(blank=True, null=True)),
                ('used_weight', models.FloatField(blank=True, null=True)),
                ('number_of_sheets', models.FloatField(blank=True, null=True)),
                ('cut_length_per_sheet', models.FloatField(blank=True, null=True)),
                ('pierce_per_sheet', models.FloatField(blank=True, null=True)),
                ('processed_mins_per_sheet', models.FloatField(blank=True, null=True)),
                ('total_planned_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('total_meters', models.FloatField(blank=True, null=True)),
                ('total_piercing', models.FloatField(blank=True, null=True)),
                ('total_used_weight', models.FloatField(blank=True, null=True)),
                ('total_no_of_sheets', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user')),
                ('material_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_material')),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
        migrations.AddField(
            model_name='all_user',
            name='role',
            field=models.ManyToManyField(blank=True, to='api.role'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user')),
            ],
        ),
        migrations.CreateModel(
            name='acc_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user')),
                ('material_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_material')),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_details')),
            ],
        ),
    ]
