# Generated by Django 4.2.27 on 2025-12-03 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 3, 16, 9, 17, 747924)),
        ),
    ]
