# Generated by Django 4.2.27 on 2025-12-03 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_details_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_details',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 3, 16, 18, 30, 110085)),
        ),
        migrations.AddField(
            model_name='programer_details',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programer_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 3, 16, 18, 30, 104597)),
        ),
        migrations.AddField(
            model_name='qa_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 3, 16, 18, 30, 104597)),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 3, 16, 18, 30, 104597)),
        ),
    ]
