# Generated by Django 6.0 on 2025-12-05 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_acc_details_date_acc_details_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 5, 10, 54, 41, 677061)),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 5, 10, 54, 41, 675589)),
        ),
        migrations.AlterField(
            model_name='programer_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 5, 10, 54, 41, 676403)),
        ),
        migrations.AlterField(
            model_name='qa_details',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 12, 5, 10, 54, 41, 676760)),
        ),
    ]
